### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Delti42** [nabil-ak/BTCFucker#1]
Log: 

> Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "btcfucker.py", line 19, in runInstance
    sendMessage(f"STARTED",pID,tID)
  File "btcfucker.py", line 85, in sendMessage
    response = webhook.execute()
  File "/home/dregan/.local/lib/python3.8/site-packages/discord_webhook/webhook.py", line 157, in execute
    response = self.api_post_request(url)
  File "/home/dregan/.local/lib/python3.8/site-packages/discord_webhook/webhook.py", line 135, in api_post_request
    response = requests.post(url, json=self.json, proxies=self.proxies,
  File "/home/dregan/.local/lib/python3.8/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/dregan/.local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/dregan/.local/lib/python3.8/site-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/home/dregan/.local/lib/python3.8/site-packages/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "/home/dregan/.local/lib/python3.8/site-packages/requests/models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "/home/dregan/.local/lib/python3.8/site-packages/requests/models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'Enter Discord Webhook': No schema supplied. Perhaps you meant http://Enter Discord Webhook?
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "btcfucker.py", line 19, in runInstance
    sendMessage(f"STARTED",pID,tID)
  File "btcfucker.py", line 85, in sendMessage
    response = webhook.execute()
  File "/home/dregan/.local/lib/python3.8/site-packages/discord_webhook/webhook.py", line 157, in execute
    response = self.api_post_request(url)
  File "/home/dregan/.local/lib/python3.8/site-packages/discord_webhook/webhook.py", line 135, in api_post_request
    response = requests.post(url, json=self.json, proxies=self.proxies,
  File "/home/dregan/.local/lib/python3.8/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/dregan/.local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/dregan/.local/lib/python3.8/site-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/home/dregan/.local/lib/python3.8/site-packages/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "/home/dregan/.local/lib/python3.8/site-packages/requests/models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "/home/dregan/.local/lib/python3.8/site-packages/requests/models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'Enter Discord Webhook': No schema supplied. Perhaps you meant http://Enter Discord Webhook?

 

How to fix it?

**Comment by nabil-ak** [comment]
Did you set your discord webhook like this in your settings.json file?

{
    **"log":"https://discord.com/api/webhooks/919322476062278660/AOQBb-DrLIsaK6oVIjJ5d0DA3ngn62TBl3SzdQF7ZyaV2aJ4DZ1dDP6ZlmovrSVcpUUh",
    "error":"https://discord.com/api/webhooks/919322476062278660/AOQBb-DrLIsaK6oVIjJ5d0DA3ngn62TBl3SzdQF7ZyaV2aJ4DZ1dDP6ZlmovrSVcpUUh",
    "success":"https://discord.com/api/webhooks/919322476062278660/AOQBb-DrLIsaK6oVIjJ5d0DA3ngn62TBl3SzdQF7ZyaV2aJ4DZ1dDP6ZlmovrSVcpUUh"**,
    "logColor":"f2902b",
    "errorColor":"ff2121",
    "sucessColor":"4BB543",
    "addressperRequest":140,
    "messageInterval":120
}

**Comment by nabil-ak** [comment]
Be aware this script is not very efficient there more efficient scripts writen in c++ on Github.
I just created the script for fun and used an external libary for the key generation.

You could use [this script](https://github.com/albertobsd/keyhunt) for example.

Another think to know is that you can create 2^160 different keys. This number is so big that its very unlikely to find bitcoins on a wallet.
